version: "3"

services:     
  sisr:
    container_name: sisr
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    build: .
    command: python BL_NN_BC.py
    volumes:
      - .:/developer
    ports:
      - "5000:5000"


