version: "3"

services:     
  sisr:
    container_name: sisr
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    build: .
    command: python sisrPredict.py testing/000087.png -s 4 -d
    volumes:
      - .:/developer
    ports:
      - "5000:5000"


