version: "3"

services:     
  sisr:
    container_name: sisr
    build: .
    command: python SISR.py #sisrPredict.py testing/000087.png -s 4 # simple_convert_dicom_to_png.py  # python BL_NN_BC.py      # python SISR.py
    volumes:
      - .:/developer
    ports:
      - "5000:5000"


